platform :ios, '8.0'
use_frameworks!

post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        # Configure Pod targets for Xcode 8 compatibility
        config.build_settings['SWIFT_VERSION'] = ‘3.0’
        config.build_settings['PROVISIONING_PROFILE_SPECIFIER'] = 'com.development.'
        config.build_settings['ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES'] = 'NO'
        config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
        config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
        config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
end

target ‘Wagespoon’ do

pod 'MFSideMenu'
pod 'Alamofire', '~> 4.4'
pod 'ObjectMapper', '~> 2.2'
pod 'AlamofireObjectMapper', '~> 4.0'

    
end
